trigger:
  branches:
    include:
    - master
    - f/*
    - feature/*
    - features/*

stages:
  - template: pipelines/stages/build.yaml

  - template: pipelines/stages/release.yaml
    parameters:
        pool: windows-2019
        environmentName: acc
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

  - template: pipelines/stages/release.yaml
    parameters:
        pool: windows-2019
        environmentName: prd
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
